### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by bradhanebury** [SkippyZA/rx-amqplib#14]
Example index.js

```
'use strict';
var RxAmqpLib = require('rx-amqplib');
```

Output:

```
node index.js
/Documents/www/node_modules/rx-amqplib/src/RxAmqpLib.ts:2
import * as Rx from 'rx';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/www/index.js:6:17)
    at Module._compile (module.js:541:32)
```

Dependencies

```
  "dependencies": {
    "rx": "~4.1.0",
    "rx-amqplib": "0.1.4"
  }
```

**Comment by SkippyZA** [comment]
Thanks for bringing this to my attention. I shall take a look at it shortly.

**Comment by SkippyZA** [comment]
I have resolved the issue. Try using `0.1.6` now.
